// This file is auto-generated by @hey-api/openapi-ts

/**
 * `PUT /admin-auth` — the resource post-state (`{configured, modules}`, the same shape
 * `GET /admin-auth` returns) plus apply metadata, so a client uses the PUT response as post-state.
 */
export type AdminAuthPutView = {
    applied: boolean;
    config_version: number;
    configured: boolean;
    modules: Array<string>;
    note: string;
};

/**
 * The admin-plane auth read (`GET /api/v1/admin/admin-auth`) — which modules guard the ADMIN surface
 * (distinct from the ingress `auth` chain). `modules` is the live `admin_auth` chain (the SAME
 * resource `PUT /api/v1/admin/admin-auth` writes), so a read-after-write is coherent. An empty chain is
 * the open (anonymous, full-authority) dev posture — `configured: false`. Never a secret.
 */
export type AdminAuthView = {
    /**
     * Whether an admin credential chain is configured. `false` = the empty chain = open dev posture.
     */
    configured: boolean;
    /**
     * The active admin-plane guard module names — the `admin_auth` chain verbatim (e.g.
     * `["admin-tokens"]`), reported in order. Empty when the admin plane is open.
     */
    modules: Array<string>;
};

/**
 * One admin audit record. `outcome` is a stable token tooling can branch on. The record is
 * HASH-CHAINED for tamper-EVIDENCE (§6.7): `hash = sha256(prev_hash | seq | ts | action | resource |
 * outcome | principal)`, and `prev_hash` is the preceding entry's `hash`. Recomputing the chain detects any
 * altered/reordered/deleted entry (detection, not prevention — a compromised host can still rewrite
 * the whole chain; prevention is shipping the log off-box to a SIEM).
 */
export type AuditEntry = {
    /**
     * The action, `noun.verb` (e.g. `hook.register`, `hook.delete`).
     */
    action: string;
    /**
     * `sha256(prev_hash | seq | ts | action | resource | outcome | principal)` — the tamper-evidence digest.
     */
    hash: string;
    /**
     * Stable outcome token: `applied` (mutation committed) | `rejected` (validation/conflict, nothing
     * changed).
     */
    outcome: string;
    /**
     * The preceding entry's `hash` (empty for the first entry of the process, or the oldest retained
     * entry whose predecessor was pruned).
     */
    prev_hash: string;
    /**
     * WHO — the authenticated principal id that attempted the mutation (`admin` for the operator
     * token; a virtual-key id or an external module's principal id otherwise; `anonymous` for the
     * explicit open admin posture). Attribution, never a credential.
     */
    principal: string;
    /**
     * The resource acted on (e.g. `hook:compress`). Never a secret.
     */
    resource: string;
    /**
     * Monotonic sequence number (1-based), unique within a process lifetime.
     */
    seq: number;
    /**
     * Unix seconds when the mutation was attempted.
     */
    ts: number;
};

/**
 * `GET /audit` — the cursor-paginated audit-log envelope (`{items, next_cursor}`, hand-rolled in the
 * audit handler).
 */
export type AuditPageView = {
    items: Array<AuditEntry>;
    next_cursor: string | null;
};

/**
 * The ingress auth chain read (`GET /api/v1/admin/auth`): the ordered module names that authenticate
 * callers + the upstream-credential mode. Never a secret — module names and the mode are config
 * identifiers, not credentials. An empty `chain` is the open front door (admits every request).
 */
export type AuthView = {
    /**
     * Ordered auth-chain module names (`[]` = open front door).
     */
    chain: Array<string>;
    /**
     * Whether the front door is open (empty chain admits unconditionally).
     */
    open: boolean;
    /**
     * `"own"` (busbar signs egress with its configured key) or `"passthrough"` (forward the caller's
     * credential upstream).
     */
    upstream_credentials: string;
};

/**
 * The compiled-in feature proof (`InfoView.build`).
 */
export type BuildInfo = {
    /**
     * Auth modules baked into this binary (e.g. `["tokens"]`; empty under `--no-default-features`).
     */
    auth_modules: Array<string>;
    /**
     * Hook plugins baked into this binary (e.g. `["ranking"]`).
     */
    hook_plugins: Array<string>;
    /**
     * The inline SWRR floor — ALWAYS `true` (compiled in unconditionally, non-removable).
     */
    weighted_floor: boolean;
};

/**
 * `POST /auth/cache/flush` — number of cached credential-decision entries dropped.
 */
export type CacheFlushView = {
    flushed: number;
};

/**
 * `POST /config/apply` — apply-a-full-config result. The change is live but not written to disk.
 */
export type ConfigApplyView = {
    applied: boolean;
    config_version: number;
    note: string;
};

/**
 * The `global_hooks` delta of a `GET /config/diff` — present only when the global wiring changed.
 */
export type ConfigDiffGlobalHooks = {
    from: Array<string>;
    to: Array<string>;
};

/**
 * The `hooks` object of a `GET /config/diff` — hook names added / removed / changed between the two
 * versions.
 */
export type ConfigDiffHooks = {
    added: Array<string>;
    changed: Array<string>;
    removed: Array<string>;
};

/**
 * `GET /config/diff` — structured hook-surface diff between two retained versions. `global_hooks` is
 * present only when the global wiring differed between the two sides.
 */
export type ConfigDiffView = {
    from: number;
    global_hooks?: ConfigDiffGlobalHooks | null;
    hooks: ConfigDiffHooks;
    to: number;
};

/**
 * `POST /config/reload` — reload-from-disk result.
 */
export type ConfigReloadView = {
    config_version: number;
    reloaded: boolean;
};

/**
 * `POST /config/rollback` — restore-a-retained-version result (the restored version + the NEW
 * config version the rollback produced).
 */
export type ConfigRollbackView = {
    config_version: number;
    restored_version: number;
};

/**
 * The result of `POST /api/v1/admin/config/validate` — a DRY-RUN: does a proposed config resolve +
 * validate, WITHOUT applying anything. `ok` is the verdict; `errors` lists every structural/resolution
 * failure at once (empty when `ok`). A well-formed request always returns 200 with this view (a valid
 * request that describes an INVALID config is `ok: false`, not an HTTP error); only a MALFORMED request
 * body is an `invalid_request`. Env-var interpolation is out of scope — this checks structure and
 * cross-reference resolution, not runtime secret presence.
 */
export type ConfigValidateView = {
    errors: Array<string>;
    ok: boolean;
};

/**
 * One recorded config version: the metadata the versions LIST shows, plus the full hook-surface
 * snapshot rollback restores. Never contains a secret (hook definitions are operator config —
 * transports, grants, deadlines).
 */
export type ConfigVersion = {
    /**
     * The acting principal (audit attribution, same handle as the audit log).
     */
    principal: string;
    /**
     * Human summary of the mutation that produced this version (e.g. `hook.register hook:x`).
     */
    summary: string;
    /**
     * Unix seconds when the mutation committed.
     */
    ts: number;
    /**
     * The `App.config_version` this snapshot corresponds to (monotonic per process).
     */
    version: number;
};

/**
 * `GET /config/versions/{v}` — one retained config version WITH its full hook-surface snapshot
 * (projected through the wire `HookView`, keyed by hook name) and the global wiring at that version.
 */
export type ConfigVersionDetailView = {
    global_hooks: Array<string>;
    hooks: {
        [key: string]: HookView;
    };
    principal: string;
    summary: string;
    ts: number;
    version: number;
};

/**
 * `GET /config/versions` — the cursor-paginated version-history envelope (`{items, next_cursor}`).
 */
export type ConfigVersionPageView = {
    items: Array<ConfigVersion>;
    next_cursor: string | null;
};

/**
 * `POST /keys` (mint) — the key metadata plus the ONCE-shown secret, and (when an AWS SigV4
 * credential was requested) the AccessKeyId + secret access key. The AWS fields are absent on a
 * bearer-only mint.
 */
export type CreatedKeyView = {
    allowed_pools: Array<string>;
    /**
     * AWS AccessKeyId (present only when `issue_aws_credential` was set). Not secret.
     */
    aws_access_key_id?: string | null;
    /**
     * AWS SigV4 secret access key — shown once (present only with an AWS credential).
     */
    aws_secret_access_key?: string | null;
    budget_period: string;
    created_at: number;
    enabled: boolean;
    id: string;
    max_budget_cents: number | null;
    name: string;
    rpm_limit: number | null;
    /**
     * The bearer secret — shown EXACTLY once, never returned by any read.
     */
    secret: string;
    tpm_limit: number | null;
};

/**
 * The EFFECTIVE config snapshot (`GET /api/v1/admin/config`) — the running configuration as busbar
 * resolved it, for drift detection (compare against your desired config) and one-shot inspection.
 * Composed from the same REDACTED reads as the individual endpoints (auth chain names, pool/model/
 * provider topology, hook definitions, global-hook wiring) — so it carries NO secret: no client
 * tokens, no provider keys, no hook payloads. Additive-only; the source-layer annotation (base vs
 * overlay) lands with the config overlay substrate.
 */
export type EffectiveConfigView = {
    auth: AuthView;
    /**
     * Names fired on every request (`global_hooks:` + any inline `global: true`).
     */
    global_hooks: Array<string>;
    hooks: Array<HookView>;
    models: Array<ModelView>;
    pools: Array<PoolView>;
    providers: Array<ProviderView>;
    /**
     * The monotonic config version at the time of this read (see `InfoView.config_version`) — so a
     * drift-detection read gets the config AND its version in one call.
     */
    version: number;
};

export type _Error = {
    error: {
        code: 'not_found' | 'unauthorized' | 'method_not_allowed' | 'forbidden' | 'invalid_request' | 'version_conflict' | 'conflict' | 'rate_limited' | 'internal';
        message: string;
    };
};

/**
 * The DESIRED settings side of `hooks/{name}/status`: busbar's registry copy of the hook's settings
 * and their version.
 */
export type HookDesiredStatus = {
    settings: {
        [key: string]: unknown;
    };
    settings_version: number;
};

/**
 * The live health of one hook's transport (`GET /api/v1/admin/hooks/{name}/health`). BEST-EFFORT: for a
 * socket transport `reachable` is `Some(true/false)` from a short-timeout connect probe; for a webhook
 * (or on a non-unix host) it is `None` (probed on demand, not here) with a `detail` note. Never fires
 * the hook — just checks whether the endpoint accepts a connection. Additive-only.
 */
export type HookHealthView = {
    /**
     * A short human note on the probe (why `None`, or the connect error class). Never a secret.
     */
    detail: string | null;
    name: string;
    /**
     * `Some(true)` = the transport accepted a connection; `Some(false)` = it did not; `None` = not
     * probed here (webhook / non-unix).
     */
    reachable: boolean | null;
    transport: HookTransportView;
};

/**
 * The REPORTED settings side of `hooks/{name}/status`: what the hook says it is actually running
 * (present only when the hook answered `status`).
 */
export type HookReportedStatus = {
    settings: {
        [key: string]: unknown;
    } | null;
    settings_version: number | null;
};

/**
 * `GET /hooks/{name}/schema` — the hook's self-described settings JSON Schema (proxied over the
 * `describe` wire message), or `null` when the hook/transport does not answer.
 */
export type HookSchemaView = {
    name: string;
    /**
     * The hook's settings JSON Schema verbatim (an arbitrary JSON object), or `null`.
     */
    schema: unknown;
};

/**
 * `GET /hooks/{name}/status` — the hook's OBSERVED state: desired vs reported settings with a
 * `drift` verdict, plus the hook's self-reported metrics. `reported`/`drift` are `null` and `note`
 * is present when the hook did not answer (fail-open); `metrics` is invariantly an array.
 */
export type HookStatusView = {
    as_of: number;
    desired: HookDesiredStatus;
    drift: boolean | null;
    /**
     * Validated + bounded self-reported metrics; each entry carries `{name, type, value}` and, when
     * the hook sent them, optional `labels`/`quantiles`/`estimated`/`ci_low`/`ci_high`/`help`/
     * `label`/`unit`/`viz`/`max` members.
     */
    metrics: Array<unknown>;
    name: string;
    /**
     * A short human note present only on the fail-open (no-answer) branch.
     */
    note?: string | null;
    reported: HookReportedStatus | null;
    /**
     * Always `"live"` (the read is a live transport query).
     */
    source: string;
};

/**
 * The transport half of a `HookView`: which wire the hook speaks and its target (socket path or
 * webhook URL — operator config, not a secret). Exactly one of `socket`/`webhook` is set.
 */
export type HookTransportView = {
    /**
     * `"socket"` or `"webhook"` (or `"none"` for a misconfigured entry with neither).
     */
    kind: string;
    /**
     * The socket path or webhook URL. `None` only if the definition set neither transport.
     */
    target: string | null;
};

/**
 * A hook definition in the registry read (`GET /api/v1/admin/hooks`, `GET /api/v1/admin/hooks/{name}`) — the
 * plugin catalog read. Projects the DEFINITION (kind, transport, grants, ordering, stage), never a
 * secret. `global` reports whether the hook fires on every request (named in `global_hooks:` or
 * declared `global: true`). Live connection status (`health`) is a separate endpoint. Additive-only.
 */
export type HookView = {
    /**
     * TAP observation stage (`"request"`/`"route"`/`"attempt"`/`"completion"`), or `None` for a gate.
     */
    at: string | null;
    /**
     * Whether this hook fires on every request (globally wired).
     */
    global: boolean;
    /**
     * `"tap"` (fire-and-forget) or `"gate"` (fire-and-wait).
     */
    kind: string;
    name: string;
    /**
     * Gate fallback on timeout/error — a CLOSED, unambiguous string union (audit #8): one of the
     * reserved terminals (`"weighted"` | `"reject"` | `"first"` | `"nothing"`) or the NAME of the
     * fallback hook the chain continues through. Unambiguous by construction: the terminal words
     * are ILLEGAL hook names on every write path (`config::RESERVED_HOOK_NAMES`), so a value in
     * the terminal set is always a terminal and anything else is always a hook reference.
     */
    on_error: string;
    /**
     * Rewrite/reject ordering key (transform-chain order + reject tie-break).
     */
    priority: number;
    /**
     * Prompt access grant: `"no"` | `"ro"` | `"rw"`.
     */
    prompt: string;
    /**
     * The hook's opaque settings map (operator/API-owned; pushed via the configure wire). Never
     * interpreted by busbar; never a secret by contract (hook settings are operator config).
     */
    settings: {
        [key: string]: unknown;
    };
    /**
     * Gate decision deadline in milliseconds.
     */
    timeout_ms: number;
    transport: HookTransportView;
    /**
     * Caller-identity access grant: `"no"` | `"ro"`.
     */
    user: string;
};

/**
 * The compiled-in plugin catalog + topology + uptime returned by `GET /api/v1/admin/info`. Powers
 * version negotiation for tooling AND the compliance-by-compilation proof: `auth_modules`/`hook_plugins` reflect
 * the ACTUAL binary (feature-gated at compile time), not config, so `--no-default-features` shows a
 * provably smaller surface. No LLM content, ever.
 */
export type InfoView = {
    build: BuildInfo;
    /**
     * Whether config-overlay persistence is enabled (`BUSBAR_CONFIG_OVERLAY` set): `true` = API-applied
     * config changes are durable across restarts; `false` = live-only (lost on restart). Lets tooling
     * tell an operator whether their runtime changes will survive a restart.
     */
    config_persistence: boolean;
    /**
     * Monotonic config version — `0` at boot, +1 per API config apply. Drift-detection: re-read and
     * compare to tell whether the running config changed. Process-local (resets on restart).
     */
    config_version: number;
    /**
     * Epoch seconds of process start — the BOOT EPOCH marker: `config_version` (and any
     * process-local counter) resets on restart, so a consumer that sees `started_at` change knows
     * to read a counter reset as "new epoch", never as "reverted" (audit minor #2 / #4).
     */
    started_at: number | null;
    topology: TopologyInfo;
    /**
     * Seconds since process start, or `None` if the start instant was never stamped.
     */
    uptime_seconds: number | null;
    /**
     * busbar semantic version (`CARGO_PKG_VERSION`).
     */
    version: string;
};

/**
 * `GET /keys/{id}/usage` — the current budget-window counters for one key, plus the fraction of the
 * tightest RPM/TPM cap remaining (`null` = uncapped). `budget_period`/`window_start` are `null`
 * when the key record could not be read.
 */
export type KeyMeteringView = {
    as_of: number;
    budget_period: string | null;
    id: string;
    rate_headroom: number | null;
    requests: number;
    spend_cents: number;
    tokens: number;
    window_start: number | null;
};

/**
 * `GET /keys` — the cursor-paginated key list envelope (`{items, next_cursor}`, hand-rolled in the
 * keys handler rather than via `Page<T>`).
 */
export type KeyPageView = {
    items: Array<KeyView>;
    next_cursor: string | null;
};

/**
 * One key's row of the per-key aggregation: the key id/name (never the secret) + its counts.
 */
export type KeyUsageView = {
    id: string;
    /**
     * The key's display name; `None` when the key was deleted after metering accumulated (history
     * outlives the key — the id still attributes it).
     */
    name: string | null;
    requests: number;
    /**
     * Busbar's derived cost estimate in MICRO-units of `currency` (1e-6 USD — integer math,
     * sub-cent precise, no float drift), from the operator's configured global prices. A consumer
     * with its own per-model catalog recomputes from the raw token split instead.
     */
    spend_micros: number;
    tokens_cache_creation: number;
    tokens_cache_read: number;
    /**
     * Uncached input tokens (normalized additive-cache convention).
     */
    tokens_input: number;
    tokens_output: number;
};

/**
 * Virtual-key metadata — the `key_meta()` shape returned by `GET /keys/{id}`, `PATCH /keys/{id}`,
 * and as each item of `GET /keys`. Never the secret or its hash.
 */
export type KeyView = {
    allowed_pools: Array<string>;
    budget_period: string;
    created_at: number;
    enabled: boolean;
    id: string;
    max_budget_cents: number | null;
    name: string;
    rpm_limit: number | null;
    tpm_limit: number | null;
};

/**
 * One (model, provider) row of the per-model aggregation.
 */
export type ModelUsageView = {
    model: string;
    provider: string;
    requests: number;
    /**
     * Busbar's derived cost estimate in MICRO-units of `currency` (1e-6 USD — integer math,
     * sub-cent precise, no float drift), from the operator's configured global prices. A consumer
     * with its own per-model catalog recomputes from the raw token split instead.
     */
    spend_micros: number;
    tokens_cache_creation: number;
    tokens_cache_read: number;
    /**
     * Uncached input tokens (normalized additive-cache convention).
     */
    tokens_input: number;
    tokens_output: number;
};

/**
 * A model lane in the topology read (`GET /api/v1/admin/models`): the config key + its upstream
 * provider. No credentials, ever.
 */
export type ModelView = {
    model: string;
    provider: string;
};

/**
 * A cursor-paginated list envelope. `items` is this page; `next_cursor` is `Some` when more remain
 * (design-admin-api-v1 §0.4). Generic over the item view so every list endpoint shares one shape.
 */
export type PageHookView = {
    items: Array<HookView>;
    next_cursor: string | null;
};

/**
 * A cursor-paginated list envelope. `items` is this page; `next_cursor` is `Some` when more remain
 * (design-admin-api-v1 §0.4). Generic over the item view so every list endpoint shares one shape.
 */
export type PageModelView = {
    items: Array<ModelView>;
    next_cursor: string | null;
};

/**
 * A cursor-paginated list envelope. `items` is this page; `next_cursor` is `Some` when more remain
 * (design-admin-api-v1 §0.4). Generic over the item view so every list endpoint shares one shape.
 */
export type PagePluginView = {
    items: Array<PluginView>;
    next_cursor: string | null;
};

/**
 * A cursor-paginated list envelope. `items` is this page; `next_cursor` is `Some` when more remain
 * (design-admin-api-v1 §0.4). Generic over the item view so every list endpoint shares one shape.
 */
export type PagePoolView = {
    items: Array<PoolView>;
    next_cursor: string | null;
};

/**
 * A cursor-paginated list envelope. `items` is this page; `next_cursor` is `Some` when more remain
 * (design-admin-api-v1 §0.4). Generic over the item view so every list endpoint shares one shape.
 */
export type PageProviderView = {
    items: Array<ProviderView>;
    next_cursor: string | null;
};

/**
 * One plugin in the plugin catalog (`GET /api/v1/admin/plugins?type=`). A plugin is either
 * COMPILED-IN (baked into the binary, feature-gated — provably removable via `--no-default-features`)
 * or EXTERNAL (registered at runtime over socket/webhook). `active` is `Some(true/false)` where
 * activation is tracked (auth modules: in the chain?; external hooks: configured = true) and `None`
 * where it is a per-pool concern not summarized here (compiled-in ranking policies). Additive-only.
 */
export type PluginView = {
    /**
     * Whether the plugin is currently active, where tracked; `None` when activation is not summarized
     * at this level.
     */
    active: boolean | null;
    /**
     * `"compiled-in"` or `"external"`.
     */
    loader: string;
    name: string;
    /**
     * For an external plugin, its transport target (socket path / webhook URL). `None` for compiled-in.
     */
    target: string | null;
    /**
     * `"auth"` or `"hooks"` — the plugin TYPE (each a distinct engine contract).
     */
    type: string;
};

/**
 * The LIVE per-pool detail read (`GET /api/v1/admin/pools/{name}`) — the reliability/capacity dashboard
 * data (design-admin-api-v1 §6.9): each member's breaker state, concurrency headroom, in-flight
 * count, latency EWMA, and success/error tallies, read from the SAME store signals the routing seam
 * ranks on. No LLM content, no credentials.
 */
export type PoolDetailView = {
    members: Array<PoolMemberStatusView>;
    name: string;
};

/**
 * One member's live status within a pool. The breaker signal is the release-exposed
 * `usable`/`cooldown_remaining_seconds` pair (a lane in breaker cooldown reports `usable: false` with the
 * seconds remaining) — the same summary `/stats` surfaces.
 */
export type PoolMemberStatusView = {
    /**
     * Free concurrency slots on this lane right now (lane-global; permits are shared across pools).
     */
    available_concurrency: number;
    /**
     * Seconds until a tripped breaker's cooldown elapses; `0` when not cooling down. (`_seconds`
     * suffix — the one unit-suffix spelling across the surface, like `uptime_seconds`.)
     */
    cooldown_remaining_seconds: number;
    /**
     * Whether the lane is hard-down/dead (distinct from a transiently-tripped breaker).
     */
    dead: boolean;
    err: number;
    /**
     * In-flight requests on this lane right now.
     */
    inflight: number;
    /**
     * Epoch seconds of the most recent trip; `None` = never tripped.
     */
    last_trip_at: number | null;
    /**
     * Latency EWMA in milliseconds, or `None` if no sample yet.
     */
    latency_ms: number | null;
    model: string;
    /**
     * Successful and errored request tallies for this lane.
     */
    ok: number;
    /**
     * MONOTONIC count of Closed→Open breaker trips on this lane. Breaker episodes are transient
     * and can open+close entirely between two polls — a consumer alerting on trips diffs this
     * count instead of trying to catch the live edge (audit #5). Carried across config apply and
     * restart with the rest of the learned health.
     */
    trip_count: number;
    /**
     * Whether the lane can currently take dispatch (breaker closed / recovered). `false` while a
     * tripped breaker cools down or the lane is dead.
     */
    usable: boolean;
    weight: number;
};

/**
 * One member of a pool: the model it targets and its SWRR weight.
 */
export type PoolMemberView = {
    model: string;
    weight: number;
};

/**
 * A pool in the topology read (`GET /api/v1/admin/pools`). Summary shape today: name + the member
 * models and their weights. LIVE per-member status (breaker state, available concurrency, latency
 * EWMA, budget/rate headroom — design-admin-api-v1 §6.9) is an additive follow-up; the field set
 * only grows.
 */
export type PoolView = {
    members: Array<PoolMemberView>;
    name: string;
};

/**
 * A provider in the topology read (`GET /api/v1/admin/providers`): the provider name + how many model
 * lanes route through it.
 */
export type ProviderView = {
    model_count: number;
    provider: string;
};

/**
 * `POST /keys/{id}/rotate` — the key metadata plus the ONCE-shown fresh bearer secret.
 */
export type RotatedKeyView = {
    allowed_pools: Array<string>;
    budget_period: string;
    created_at: number;
    enabled: boolean;
    id: string;
    max_budget_cents: number | null;
    name: string;
    rpm_limit: number | null;
    /**
     * The fresh bearer secret — shown EXACTLY once.
     */
    secret: string;
    tpm_limit: number | null;
};

/**
 * Pool/model/provider counts (`InfoView.topology`).
 */
export type TopologyInfo = {
    models: number;
    pools: number;
    providers: number;
};

/**
 * The raw consumption counts + the derived spend estimate — the one shape shared by `total`,
 * `by_model` rows, and `by_key` rows, so a consumer writes ONE aggregation reader.
 */
export type UsageBreakdown = {
    requests: number;
    /**
     * Busbar's derived cost estimate in MICRO-units of `currency` (1e-6 USD — integer math,
     * sub-cent precise, no float drift), from the operator's configured global prices. A consumer
     * with its own per-model catalog recomputes from the raw token split instead.
     */
    spend_micros: number;
    tokens_cache_creation: number;
    tokens_cache_read: number;
    /**
     * Uncached input tokens (normalized additive-cache convention).
     */
    tokens_input: number;
    tokens_output: number;
};

/**
 * Fleet METERING read (`GET /api/v1/admin/usage`) — the FinOps surface. Design principle:
 * busbar exposes the RAW INPUTS of cost, not just its own number. Every row carries the full token
 * SPLIT (input / output / cache-read / cache-creation — each prices differently), so a consumer
 * with its own (special/negotiated) price catalog reconstructs cost independently; `spend_micros`
 * is busbar's DERIVED estimate from the operator's configured global prices, computed at read time
 * (raw counts are what's stored — a price change re-prices history consistently).
 *
 * Time base — THE PINNED SHAPE RULING (external review R3 #1): a usage response is ALWAYS exactly
 * ONE fixed UTC-day metering bucket (`window`). `?window=<bucket-start-epoch>` selects a PAST
 * bucket (default: the current one); a multi-window series is the CLIENT fetching N buckets — or
 * a future additive `?from=&to=` returning an ARRAY OF THIS SAME PER-BUCKET SHAPE, never a
 * differently-shaped merged view. Billing periods aggregate client-side from day buckets (raw
 * counts are stored, so the math is exact). Deliberately decoupled from per-key budget windows so
 * per-model aggregation across keys is well-defined; budget ENFORCEMENT state lives on
 * `GET /keys/{id}/usage`, not here. Empty aggregations when governance is disabled. No secrets —
 * key ids/names only, never a token.
 *
 * LEDGER RULE (one loud contract sentence): `spend_micros` is a MUTABLE ESTIMATE — derived at
 * read time from the operator's CURRENT prices, so a price change re-prices history. Never store
 * it as a ledger charge; bill from the raw token split.
 */
export type UsageView = {
    /**
     * Freshness marker: the epoch this read was computed at (counters accumulate live).
     */
    as_of: number;
    /**
     * Per-key aggregation (same raw-split shape). CAPPED at the top 1000 rows by spend (the
     * FinOps-relevant ordering); `by_key_truncated` says the cap fired — never a silent cut.
     */
    by_key: Array<KeyUsageView>;
    /**
     * True when `by_key` was truncated to the cap (a deployment with more active keys than the
     * cap). `by_model` is never capped (bounded by the configured model fleet).
     */
    by_key_truncated: boolean;
    /**
     * Per-(model, provider) aggregation — cost attribution by model (the FinOps unit).
     */
    by_model: Array<ModelUsageView>;
    /**
     * The denomination of every `spend_micros` in this response (`USAGE_CURRENCY`).
     */
    currency: string;
    /**
     * The summed remainder BEYOND the `by_key` cap — present exactly when `by_key_truncated`, so
     * every unit of consumption is attributable at least to "others" (FinOps completeness:
     * `total == sum(by_key) + others`).
     */
    others?: UsageBreakdown | null;
    total: UsageBreakdown;
    /**
     * The UTC-day metering bucket this response aggregates: `[start, end)` epoch seconds.
     */
    window: UsageWindow;
};

/**
 * A metering window: `[start, end)` epoch seconds.
 */
export type UsageWindow = {
    end: number;
    start: number;
};

export type GetApiV1AdminAdminAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/admin-auth';
};

export type GetApiV1AdminAdminAuthErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminAdminAuthError = GetApiV1AdminAdminAuthErrors[keyof GetApiV1AdminAdminAuthErrors];

export type GetApiV1AdminAdminAuthResponses = {
    /**
     * OK
     */
    200: AdminAuthView;
};

export type GetApiV1AdminAdminAuthResponse = GetApiV1AdminAdminAuthResponses[keyof GetApiV1AdminAdminAuthResponses];

export type PutApiV1AdminAdminAuthData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/admin-auth';
};

export type PutApiV1AdminAdminAuthErrors = {
    /**
     * Unknown module / malformed body (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Stale `If-Match` (`version_conflict`), or the new chain would lock the caller out (error code `conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PutApiV1AdminAdminAuthError = PutApiV1AdminAdminAuthErrors[keyof PutApiV1AdminAdminAuthErrors];

export type PutApiV1AdminAdminAuthResponses = {
    /**
     * The resource + apply metadata: `{configured, modules, applied, config_version, note}`
     */
    200: AdminAuthPutView;
};

export type PutApiV1AdminAdminAuthResponse = PutApiV1AdminAdminAuthResponses[keyof PutApiV1AdminAdminAuthResponses];

export type GetApiV1AdminAuditData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by exact action (e.g. `hook.register`)
         */
        action?: string;
        /**
         * Filter by exact resource (e.g. `hook:x`)
         */
        resource?: string;
        /**
         * Page size (default 200, max 1000)
         */
        limit?: string;
        /**
         * Opaque continuation cursor from `next_cursor`
         */
        cursor?: string;
    };
    url: '/api/v1/admin/audit';
};

export type GetApiV1AdminAuditErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminAuditError = GetApiV1AdminAuditErrors[keyof GetApiV1AdminAuditErrors];

export type GetApiV1AdminAuditResponses = {
    /**
     * OK
     */
    200: AuditPageView;
};

export type GetApiV1AdminAuditResponse = GetApiV1AdminAuditResponses[keyof GetApiV1AdminAuditResponses];

export type GetApiV1AdminAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth';
};

export type GetApiV1AdminAuthErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminAuthError = GetApiV1AdminAuthErrors[keyof GetApiV1AdminAuthErrors];

export type GetApiV1AdminAuthResponses = {
    /**
     * OK
     */
    200: AuthView;
};

export type GetApiV1AdminAuthResponse = GetApiV1AdminAuthResponses[keyof GetApiV1AdminAuthResponses];

export type PostApiV1AdminAuthCacheFlushData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/auth/cache/flush';
};

export type PostApiV1AdminAuthCacheFlushErrors = {
    /**
     * Malformed body (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminAuthCacheFlushError = PostApiV1AdminAuthCacheFlushErrors[keyof PostApiV1AdminAuthCacheFlushErrors];

export type PostApiV1AdminAuthCacheFlushResponses = {
    /**
     * `{flushed}` — entries dropped
     */
    200: CacheFlushView;
};

export type PostApiV1AdminAuthCacheFlushResponse = PostApiV1AdminAuthCacheFlushResponses[keyof PostApiV1AdminAuthCacheFlushResponses];

export type GetApiV1AdminConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/config';
};

export type GetApiV1AdminConfigErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminConfigError = GetApiV1AdminConfigErrors[keyof GetApiV1AdminConfigErrors];

export type GetApiV1AdminConfigResponses = {
    /**
     * OK
     */
    200: EffectiveConfigView;
};

export type GetApiV1AdminConfigResponse = GetApiV1AdminConfigResponses[keyof GetApiV1AdminConfigResponses];

export type PostApiV1AdminConfigApplyData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/config/apply';
};

export type PostApiV1AdminConfigApplyErrors = {
    /**
     * Invalid config (error code `invalid_request`); nothing changed
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Stale `If-Match` (error code `version_conflict` — re-read and retry)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminConfigApplyError = PostApiV1AdminConfigApplyErrors[keyof PostApiV1AdminConfigApplyErrors];

export type PostApiV1AdminConfigApplyResponses = {
    /**
     * `{applied, config_version, note}`
     */
    200: ConfigApplyView;
};

export type PostApiV1AdminConfigApplyResponse = PostApiV1AdminConfigApplyResponses[keyof PostApiV1AdminConfigApplyResponses];

export type GetApiV1AdminConfigDiffData = {
    body?: never;
    path?: never;
    query: {
        from: number;
        to: number;
    };
    url: '/api/v1/admin/config/diff';
};

export type GetApiV1AdminConfigDiffErrors = {
    /**
     * Missing/non-numeric `from` or `to` (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Either version pruned or never recorded (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminConfigDiffError = GetApiV1AdminConfigDiffErrors[keyof GetApiV1AdminConfigDiffErrors];

export type GetApiV1AdminConfigDiffResponses = {
    /**
     * The diff (hooks added/removed/changed + global-wiring delta)
     */
    200: ConfigDiffView;
};

export type GetApiV1AdminConfigDiffResponse = GetApiV1AdminConfigDiffResponses[keyof GetApiV1AdminConfigDiffResponses];

export type PostApiV1AdminConfigReloadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/config/reload';
};

export type PostApiV1AdminConfigReloadErrors = {
    /**
     * Disk config invalid or no config files (error code `invalid_request`); nothing changed
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminConfigReloadError = PostApiV1AdminConfigReloadErrors[keyof PostApiV1AdminConfigReloadErrors];

export type PostApiV1AdminConfigReloadResponses = {
    /**
     * `{reloaded, config_version}`
     */
    200: ConfigReloadView;
};

export type PostApiV1AdminConfigReloadResponse = PostApiV1AdminConfigReloadResponses[keyof PostApiV1AdminConfigReloadResponses];

export type PostApiV1AdminConfigRollbackData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/config/rollback';
};

export type PostApiV1AdminConfigRollbackErrors = {
    /**
     * Snapshot fails re-validation (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Target version not retained (error code `not_found`)
     */
    404: _Error;
    /**
     * Stale `If-Match` (error code `version_conflict` — re-read and retry)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminConfigRollbackError = PostApiV1AdminConfigRollbackErrors[keyof PostApiV1AdminConfigRollbackErrors];

export type PostApiV1AdminConfigRollbackResponses = {
    /**
     * `{restored_version, config_version}`
     */
    200: ConfigRollbackView;
};

export type PostApiV1AdminConfigRollbackResponse = PostApiV1AdminConfigRollbackResponses[keyof PostApiV1AdminConfigRollbackResponses];

export type PostApiV1AdminConfigValidateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/config/validate';
};

export type PostApiV1AdminConfigValidateErrors = {
    /**
     * Malformed request body (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminConfigValidateError = PostApiV1AdminConfigValidateErrors[keyof PostApiV1AdminConfigValidateErrors];

export type PostApiV1AdminConfigValidateResponses = {
    /**
     * Verdict `{ok, errors}` (even for an invalid config)
     */
    200: ConfigValidateView;
};

export type PostApiV1AdminConfigValidateResponse = PostApiV1AdminConfigValidateResponses[keyof PostApiV1AdminConfigValidateResponses];

export type GetApiV1AdminConfigVersionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size (default 100, max 1000)
         */
        limit?: string;
        /**
         * Opaque continuation cursor from `next_cursor`
         */
        cursor?: string;
    };
    url: '/api/v1/admin/config/versions';
};

export type GetApiV1AdminConfigVersionsErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminConfigVersionsError = GetApiV1AdminConfigVersionsErrors[keyof GetApiV1AdminConfigVersionsErrors];

export type GetApiV1AdminConfigVersionsResponses = {
    /**
     * OK
     */
    200: ConfigVersionPageView;
};

export type GetApiV1AdminConfigVersionsResponse = GetApiV1AdminConfigVersionsResponses[keyof GetApiV1AdminConfigVersionsResponses];

export type GetApiV1AdminConfigVersionsByVData = {
    body?: never;
    path: {
        v: number;
    };
    query?: never;
    url: '/api/v1/admin/config/versions/{v}';
};

export type GetApiV1AdminConfigVersionsByVErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Pruned or never recorded (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminConfigVersionsByVError = GetApiV1AdminConfigVersionsByVErrors[keyof GetApiV1AdminConfigVersionsByVErrors];

export type GetApiV1AdminConfigVersionsByVResponses = {
    /**
     * The version (metadata + hooks + global_hooks)
     */
    200: ConfigVersionDetailView;
};

export type GetApiV1AdminConfigVersionsByVResponse = GetApiV1AdminConfigVersionsByVResponses[keyof GetApiV1AdminConfigVersionsByVResponses];

export type GetApiV1AdminHooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/hooks';
};

export type GetApiV1AdminHooksErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminHooksError = GetApiV1AdminHooksErrors[keyof GetApiV1AdminHooksErrors];

export type GetApiV1AdminHooksResponses = {
    /**
     * OK
     */
    200: PageHookView;
};

export type GetApiV1AdminHooksResponse = GetApiV1AdminHooksResponses[keyof GetApiV1AdminHooksResponses];

export type PostApiV1AdminHooksData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/admin/hooks';
};

export type PostApiV1AdminHooksErrors = {
    /**
     * Malformed body or invalid definition (`invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * hooks-register principal may not register a content-seeing (`prompt`/`user`) or `global: true` hook (`forbidden`, §6.3)
     */
    403: _Error;
    /**
     * Base-defined hook (edit config.yaml), grant change on an existing hook, or stale `If-Match` (`version_conflict`, §6.4)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminHooksError = PostApiV1AdminHooksErrors[keyof PostApiV1AdminHooksErrors];

export type PostApiV1AdminHooksResponses = {
    /**
     * Replaced — the name existed (same-grant re-register; body is the hook definition)
     */
    200: HookView;
    /**
     * Registered — the name is NEW (body is the hook definition)
     */
    201: HookView;
};

export type PostApiV1AdminHooksResponse = PostApiV1AdminHooksResponses[keyof PostApiV1AdminHooksResponses];

export type DeleteApiV1AdminHooksByNameData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}';
};

export type DeleteApiV1AdminHooksByNameErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * A `hooks-register` principal may not delete a content-seeing (`prompt`/`user`) or `global` hook (error code `forbidden`, §6.3)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
    /**
     * Base-defined hook — read-only via the API; edit config.yaml (error code `conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type DeleteApiV1AdminHooksByNameError = DeleteApiV1AdminHooksByNameErrors[keyof DeleteApiV1AdminHooksByNameErrors];

export type DeleteApiV1AdminHooksByNameResponses = {
    /**
     * Removed
     */
    204: void;
};

export type DeleteApiV1AdminHooksByNameResponse = DeleteApiV1AdminHooksByNameResponses[keyof DeleteApiV1AdminHooksByNameResponses];

export type GetApiV1AdminHooksByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}';
};

export type GetApiV1AdminHooksByNameErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminHooksByNameError = GetApiV1AdminHooksByNameErrors[keyof GetApiV1AdminHooksByNameErrors];

export type GetApiV1AdminHooksByNameResponses = {
    /**
     * OK
     */
    200: HookView;
};

export type GetApiV1AdminHooksByNameResponse = GetApiV1AdminHooksByNameResponses[keyof GetApiV1AdminHooksByNameResponses];

export type PutApiV1AdminHooksByNameData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}';
};

export type PutApiV1AdminHooksByNameErrors = {
    /**
     * Invalid definition (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * A `hooks-register` principal may not replace a hook into a content-seeing (`prompt`/`user`) or `global` form (error code `forbidden`, §6.3)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
    /**
     * Base-defined hook, grant change (`conflict`), or stale `If-Match` (`version_conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PutApiV1AdminHooksByNameError = PutApiV1AdminHooksByNameErrors[keyof PutApiV1AdminHooksByNameErrors];

export type PutApiV1AdminHooksByNameResponses = {
    /**
     * The replaced hook
     */
    200: HookView;
};

export type PutApiV1AdminHooksByNameResponse = PutApiV1AdminHooksByNameResponses[keyof PutApiV1AdminHooksByNameResponses];

export type GetApiV1AdminHooksByNameHealthData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}/health';
};

export type GetApiV1AdminHooksByNameHealthErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminHooksByNameHealthError = GetApiV1AdminHooksByNameHealthErrors[keyof GetApiV1AdminHooksByNameHealthErrors];

export type GetApiV1AdminHooksByNameHealthResponses = {
    /**
     * OK (`reachable` may be null for webhook/non-unix)
     */
    200: HookHealthView;
};

export type GetApiV1AdminHooksByNameHealthResponse = GetApiV1AdminHooksByNameHealthResponses[keyof GetApiV1AdminHooksByNameHealthResponses];

export type GetApiV1AdminHooksByNameSchemaData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}/schema';
};

export type GetApiV1AdminHooksByNameSchemaErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminHooksByNameSchemaError = GetApiV1AdminHooksByNameSchemaErrors[keyof GetApiV1AdminHooksByNameSchemaErrors];

export type GetApiV1AdminHooksByNameSchemaResponses = {
    /**
     * `{name, schema}` (`schema` null when the hook doesn't answer describe)
     */
    200: HookSchemaView;
};

export type GetApiV1AdminHooksByNameSchemaResponse = GetApiV1AdminHooksByNameSchemaResponses[keyof GetApiV1AdminHooksByNameSchemaResponses];

export type PatchApiV1AdminHooksByNameSettingsData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}/settings';
};

export type PatchApiV1AdminHooksByNameSettingsErrors = {
    /**
     * Hook did not acknowledge (error code `invalid_request`); nothing committed
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * A `hooks-register` principal may not push settings to a content-seeing (`prompt`/`user`) or `global` hook (error code `forbidden`, §6.3)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
    /**
     * Base-defined hook (`conflict`) or stale `If-Match` (`version_conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PatchApiV1AdminHooksByNameSettingsError = PatchApiV1AdminHooksByNameSettingsErrors[keyof PatchApiV1AdminHooksByNameSettingsErrors];

export type PatchApiV1AdminHooksByNameSettingsResponses = {
    /**
     * Acked + committed (the updated hook)
     */
    200: HookView;
};

export type PatchApiV1AdminHooksByNameSettingsResponse = PatchApiV1AdminHooksByNameSettingsResponses[keyof PatchApiV1AdminHooksByNameSettingsResponses];

export type GetApiV1AdminHooksByNameStatusData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/hooks/{name}/status';
};

export type GetApiV1AdminHooksByNameStatusErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown hook (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminHooksByNameStatusError = GetApiV1AdminHooksByNameStatusErrors[keyof GetApiV1AdminHooksByNameStatusErrors];

export type GetApiV1AdminHooksByNameStatusResponses = {
    /**
     * `{name, desired, reported, drift, metrics, as_of, source}`
     */
    200: HookStatusView;
};

export type GetApiV1AdminHooksByNameStatusResponse = GetApiV1AdminHooksByNameStatusResponses[keyof GetApiV1AdminHooksByNameStatusResponses];

export type GetApiV1AdminInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/info';
};

export type GetApiV1AdminInfoErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminInfoError = GetApiV1AdminInfoErrors[keyof GetApiV1AdminInfoErrors];

export type GetApiV1AdminInfoResponses = {
    /**
     * OK
     */
    200: InfoView;
};

export type GetApiV1AdminInfoResponse = GetApiV1AdminInfoResponses[keyof GetApiV1AdminInfoResponses];

export type GetApiV1AdminKeysData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by enabled state (`true`|`false`)
         */
        enabled?: string;
        /**
         * Filter by key-id prefix
         */
        prefix?: string;
        /**
         * Page size (default 200, max 1000)
         */
        limit?: string;
        /**
         * Opaque continuation cursor from `next_cursor`
         */
        cursor?: string;
    };
    url: '/api/v1/admin/keys';
};

export type GetApiV1AdminKeysErrors = {
    /**
     * Malformed/foreign pagination cursor (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminKeysError = GetApiV1AdminKeysErrors[keyof GetApiV1AdminKeysErrors];

export type GetApiV1AdminKeysResponses = {
    /**
     * `{items, next_cursor}` — the cursor page envelope (next_cursor null at end)
     */
    200: KeyPageView;
};

export type GetApiV1AdminKeysResponse = GetApiV1AdminKeysResponses[keyof GetApiV1AdminKeysResponses];

export type PostApiV1AdminKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/keys';
};

export type PostApiV1AdminKeysErrors = {
    /**
     * Malformed body / invalid budget or rate (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * An Idempotency-Key request is already in flight (error code `conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminKeysError = PostApiV1AdminKeysErrors[keyof PostApiV1AdminKeysErrors];

export type PostApiV1AdminKeysResponses = {
    /**
     * Created (body includes the once-shown secret)
     */
    201: CreatedKeyView;
};

export type PostApiV1AdminKeysResponse = PostApiV1AdminKeysResponses[keyof PostApiV1AdminKeysResponses];

export type DeleteApiV1AdminKeysByIdData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/keys/{id}';
};

export type DeleteApiV1AdminKeysByIdErrors = {
    /**
     * Malformed `If-Match` (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown key (error code `not_found`)
     */
    404: _Error;
    /**
     * Stale `If-Match` ETag (error code `version_conflict` — re-read and retry)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type DeleteApiV1AdminKeysByIdError = DeleteApiV1AdminKeysByIdErrors[keyof DeleteApiV1AdminKeysByIdErrors];

export type DeleteApiV1AdminKeysByIdResponses = {
    /**
     * Revoked — No Content
     */
    204: void;
};

export type DeleteApiV1AdminKeysByIdResponse = DeleteApiV1AdminKeysByIdResponses[keyof DeleteApiV1AdminKeysByIdResponses];

export type GetApiV1AdminKeysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/keys/{id}';
};

export type GetApiV1AdminKeysByIdErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown key (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminKeysByIdError = GetApiV1AdminKeysByIdErrors[keyof GetApiV1AdminKeysByIdErrors];

export type GetApiV1AdminKeysByIdResponses = {
    /**
     * Key metadata (+ `ETag` header)
     */
    200: KeyView;
};

export type GetApiV1AdminKeysByIdResponse = GetApiV1AdminKeysByIdResponses[keyof GetApiV1AdminKeysByIdResponses];

export type PatchApiV1AdminKeysByIdData = {
    body?: never;
    headers?: {
        /**
         * Optimistic concurrency: the resource's ETag from a prior read (or the ETag returned by the previous mutation). Stale = 409 `version_conflict` (re-read and retry), nothing changes; absent or `*` = unconditional.
         */
        'If-Match'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/keys/{id}';
};

export type PatchApiV1AdminKeysByIdErrors = {
    /**
     * Invalid budget/rate (error code `invalid_request`)
     */
    400: _Error;
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown key (error code `not_found`)
     */
    404: _Error;
    /**
     * Stale `If-Match` ETag (error code `version_conflict` — re-read and retry)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PatchApiV1AdminKeysByIdError = PatchApiV1AdminKeysByIdErrors[keyof PatchApiV1AdminKeysByIdErrors];

export type PatchApiV1AdminKeysByIdResponses = {
    /**
     * Updated metadata
     */
    200: KeyView;
};

export type PatchApiV1AdminKeysByIdResponse = PatchApiV1AdminKeysByIdResponses[keyof PatchApiV1AdminKeysByIdResponses];

export type PostApiV1AdminKeysByIdRotateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/keys/{id}/rotate';
};

export type PostApiV1AdminKeysByIdRotateErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `full` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown key (error code `not_found`)
     */
    404: _Error;
    /**
     * An Idempotency-Key request is already in flight (error code `conflict`)
     */
    409: _Error;
    /**
     * Per-principal mutation budget exhausted (error code `rate_limited`; `Retry-After` header)
     */
    429: _Error;
};

export type PostApiV1AdminKeysByIdRotateError = PostApiV1AdminKeysByIdRotateErrors[keyof PostApiV1AdminKeysByIdRotateErrors];

export type PostApiV1AdminKeysByIdRotateResponses = {
    /**
     * Rotated (body includes the once-shown new secret; an Idempotency-Key retry replays it verbatim)
     */
    200: RotatedKeyView;
};

export type PostApiV1AdminKeysByIdRotateResponse = PostApiV1AdminKeysByIdRotateResponses[keyof PostApiV1AdminKeysByIdRotateResponses];

export type GetApiV1AdminKeysByIdUsageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/keys/{id}/usage';
};

export type GetApiV1AdminKeysByIdUsageErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown key (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminKeysByIdUsageError = GetApiV1AdminKeysByIdUsageErrors[keyof GetApiV1AdminKeysByIdUsageErrors];

export type GetApiV1AdminKeysByIdUsageResponses = {
    /**
     * Budget-window counters + `rate_headroom` (fraction of the tightest RPM/TPM cap left; null = uncapped)
     */
    200: KeyMeteringView;
};

export type GetApiV1AdminKeysByIdUsageResponse = GetApiV1AdminKeysByIdUsageResponses[keyof GetApiV1AdminKeysByIdUsageResponses];

export type GetApiV1AdminModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/models';
};

export type GetApiV1AdminModelsErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminModelsError = GetApiV1AdminModelsErrors[keyof GetApiV1AdminModelsErrors];

export type GetApiV1AdminModelsResponses = {
    /**
     * OK
     */
    200: PageModelView;
};

export type GetApiV1AdminModelsResponse = GetApiV1AdminModelsResponses[keyof GetApiV1AdminModelsResponses];

export type GetApiV1AdminOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/openapi.json';
};

export type GetApiV1AdminOpenapiJsonErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminOpenapiJsonError = GetApiV1AdminOpenapiJsonErrors[keyof GetApiV1AdminOpenapiJsonErrors];

export type GetApiV1AdminOpenapiJsonResponses = {
    /**
     * An OpenAPI 3.1 document (this document's shape)
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1AdminOpenapiJsonResponse = GetApiV1AdminOpenapiJsonResponses[keyof GetApiV1AdminOpenapiJsonResponses];

export type GetApiV1AdminPluginsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plugin type: `auth` | `hooks` (required)
         */
        type: string;
    };
    url: '/api/v1/admin/plugins';
};

export type GetApiV1AdminPluginsErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminPluginsError = GetApiV1AdminPluginsErrors[keyof GetApiV1AdminPluginsErrors];

export type GetApiV1AdminPluginsResponses = {
    /**
     * OK
     */
    200: PagePluginView;
};

export type GetApiV1AdminPluginsResponse = GetApiV1AdminPluginsResponses[keyof GetApiV1AdminPluginsResponses];

export type GetApiV1AdminPoolsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `true` inlines each member's live status (same row shape as /pools/{name})
         */
        detail?: string;
    };
    url: '/api/v1/admin/pools';
};

export type GetApiV1AdminPoolsErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminPoolsError = GetApiV1AdminPoolsErrors[keyof GetApiV1AdminPoolsErrors];

export type GetApiV1AdminPoolsResponses = {
    /**
     * OK
     */
    200: PagePoolView;
};

export type GetApiV1AdminPoolsResponse = GetApiV1AdminPoolsResponses[keyof GetApiV1AdminPoolsResponses];

export type GetApiV1AdminPoolsByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/api/v1/admin/pools/{name}';
};

export type GetApiV1AdminPoolsByNameErrors = {
    /**
     * Missing/invalid admin credential (error code `unauthorized`)
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
    /**
     * Unknown pool (error code `not_found`)
     */
    404: _Error;
};

export type GetApiV1AdminPoolsByNameError = GetApiV1AdminPoolsByNameErrors[keyof GetApiV1AdminPoolsByNameErrors];

export type GetApiV1AdminPoolsByNameResponses = {
    /**
     * OK
     */
    200: PoolDetailView;
};

export type GetApiV1AdminPoolsByNameResponse = GetApiV1AdminPoolsByNameResponses[keyof GetApiV1AdminPoolsByNameResponses];

export type GetApiV1AdminProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/providers';
};

export type GetApiV1AdminProvidersErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminProvidersError = GetApiV1AdminProvidersErrors[keyof GetApiV1AdminProvidersErrors];

export type GetApiV1AdminProvidersResponses = {
    /**
     * OK
     */
    200: PageProviderView;
};

export type GetApiV1AdminProvidersResponse = GetApiV1AdminProvidersResponses[keyof GetApiV1AdminProvidersResponses];

export type GetApiV1AdminUsageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A PAST UTC-day bucket start epoch (default: current bucket). The response is always ONE bucket; spend_micros is a read-time estimate — bill from the raw token split, never store spend_micros as a ledger charge
         */
        window?: string;
    };
    url: '/api/v1/admin/usage';
};

export type GetApiV1AdminUsageErrors = {
    /**
     * Missing/invalid admin credential
     */
    401: _Error;
    /**
     * Authenticated but under-scoped: requires `read-only` (error code `forbidden`)
     */
    403: _Error;
};

export type GetApiV1AdminUsageError = GetApiV1AdminUsageErrors[keyof GetApiV1AdminUsageErrors];

export type GetApiV1AdminUsageResponses = {
    /**
     * OK
     */
    200: UsageView;
};

export type GetApiV1AdminUsageResponse = GetApiV1AdminUsageResponses[keyof GetApiV1AdminUsageResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};